apiVersion: apps/v1
kind: Deployment
metadata: 
 name: hell-app
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
      app: demo-app
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
        tier: backend
    spec:
      containers:
        - name: demo-app
          image: demo-app
          imagePullPolicy: Never
