apiVersion: apps/v1
kind: Deployment
metadata: 
 name: demo-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
      app: demo-app
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
        tier: backend
    spec:
      containers:
        - name: demo-app-pod
          image: abhinav153/demo-app-repo:v2
