apiVersion: apps/v1
kind: Deployment
metadata: 
 name: hell-app
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
      app: hell
  template:
    metadata:
      name: hell
      labels:
        app: hell
        tier: backend
    spec:
      containers:
        - name: hell
          image: hell
          imagePullPolicy: Never
