apiVersion: v1
kind: Service
metadata:
  name: hell-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
      app: hell
      tier: backend
